// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persist;

#nullable disable

namespace Persist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240909113052_AutSchema")]
    partial class AutSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Persist.Entities.ApplicationDeployedOnServerEntity", b =>
                {
                    b.Property<string>("ServerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApplicationPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ServerId", "ApplicationId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ApplicationDeployedOnServer");
                });

            modelBuilder.Entity("Persist.Entities.ApplicationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("Internal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Application");
                });

            modelBuilder.Entity("Persist.Entities.CustomerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FirstInteraction")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FiscalIdentification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastInteraction")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Persist.Entities.CustomerHaveLicenceToApplicationEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("BeginingSupport")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndingSupport")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerId", "ApplicationId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("CustomerHaveLicenceToApplications");
                });

            modelBuilder.Entity("Persist.Entities.ErrorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("InterventionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SeverityId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SeverityId");

                    b.HasIndex("StatusId");

                    b.ToTable("Error");
                });

            modelBuilder.Entity("Persist.Entities.ErrorStatusEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ErrorStatus");

                    b.HasData(
                        new
                        {
                            Id = "b957fe19-8732-4d57-b248-c0b1268f9e04",
                            Title = "Non Résolue"
                        },
                        new
                        {
                            Id = "2975ba97-b760-4309-a366-d833e49febc9",
                            Title = "En cours"
                        },
                        new
                        {
                            Id = "8d64ad28-1879-4356-b88b-a20be0022639",
                            Title = "Résolue"
                        });
                });

            modelBuilder.Entity("Persist.Entities.HashPasswordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsForgotten")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("HashPassword");
                });

            modelBuilder.Entity("Persist.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("OldToken")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Persist.Entities.ServerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Cost")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerWhoOwnServerId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("HasToMakeSupportSince")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HostedSince")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("StopHost")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerWhoOwnServerId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Server");
                });

            modelBuilder.Entity("Persist.Entities.SeverityLevelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SeverityLevel");

                    b.HasData(
                        new
                        {
                            Id = "7993fd1f-bc10-494d-83cb-002c58873ff6",
                            Title = "Faible"
                        },
                        new
                        {
                            Id = "281df6fe-3402-4a4b-b579-db92786dd61e",
                            Title = "Modéré"
                        },
                        new
                        {
                            Id = "bd546955-66ca-4202-8e79-e60c414ce82c",
                            Title = "Élevé"
                        },
                        new
                        {
                            Id = "12ae4ac9-59d7-4630-b361-514d3297258",
                            Title = "Critique"
                        });
                });

            modelBuilder.Entity("Persist.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashPasswordId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshTokenId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HashPasswordId");

                    b.HasIndex("RefreshTokenId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Persist.Entities.ApplicationDeployedOnServerEntity", b =>
                {
                    b.HasOne("Persist.Entities.ApplicationEntity", "Application")
                        .WithMany("ApplicationDeployedOnServers")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persist.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Persist.Entities.ServerEntity", "Server")
                        .WithMany("ApplicationDeployedOnServers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Customer");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Persist.Entities.CustomerHaveLicenceToApplicationEntity", b =>
                {
                    b.HasOne("Persist.Entities.ApplicationEntity", "Application")
                        .WithMany("CustomerHaveLicenceToApplication")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persist.Entities.CustomerEntity", "Customer")
                        .WithMany("CustomerHaveLicenceToApplication")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Persist.Entities.ErrorEntity", b =>
                {
                    b.HasOne("Persist.Entities.ApplicationEntity", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persist.Entities.ServerEntity", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persist.Entities.SeverityLevelEntity", "Severity")
                        .WithMany("Errors")
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persist.Entities.ErrorStatusEntity", "Status")
                        .WithMany("Errors")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Server");

                    b.Navigation("Severity");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Persist.Entities.HashPasswordEntity", b =>
                {
                    b.HasOne("Persist.Entities.UserEntity", null)
                        .WithMany("OldppHashPasswords")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("Persist.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Persist.Entities.UserEntity", null)
                        .WithMany("OldRefreshTokens")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("Persist.Entities.ServerEntity", b =>
                {
                    b.HasOne("Persist.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerWhoOwnServerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Persist.Entities.UserEntity", b =>
                {
                    b.HasOne("Persist.Entities.HashPasswordEntity", "HashPasswordEntity")
                        .WithMany()
                        .HasForeignKey("HashPasswordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persist.Entities.RefreshTokenEntity", "RefreshToken")
                        .WithMany()
                        .HasForeignKey("RefreshTokenId");

                    b.Navigation("HashPasswordEntity");

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("Persist.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("ApplicationDeployedOnServers");

                    b.Navigation("CustomerHaveLicenceToApplication");
                });

            modelBuilder.Entity("Persist.Entities.CustomerEntity", b =>
                {
                    b.Navigation("CustomerHaveLicenceToApplication");
                });

            modelBuilder.Entity("Persist.Entities.ErrorStatusEntity", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("Persist.Entities.ServerEntity", b =>
                {
                    b.Navigation("ApplicationDeployedOnServers");
                });

            modelBuilder.Entity("Persist.Entities.SeverityLevelEntity", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("Persist.Entities.UserEntity", b =>
                {
                    b.Navigation("OldRefreshTokens");

                    b.Navigation("OldppHashPasswords");
                });
#pragma warning restore 612, 618
        }
    }
}
